proyectofinal/apps/comentarios/urls.py
from django.urls import path, include
from . import views

app_name='comentarios'

urlpatterns = [
	
	path('Agregar/<int:pk>', views.Agregar, name='agregar_comentarios'),
	path('Borrar/<int:pk>', views.BorrarComentario.as_view(), name="borrar_comentario"),
	path('Modificar/<int:pk>', views.ModificaComentario.as_view(), name="modificar_comentario"),
]

proyectofinal/apps/noticias/urls.py
from django.urls import path, include
from . import views

app_name='noticias'

urlpatterns = [
    path('Crear', views.CrearNoticiaC.as_view(), name="crear_noticia"),
      # Noticias del usuario 
    path('mis-noticias', views.MisNoticias, name="misNoticias"),
     # Detalle de una noticia
    path('detalle-noticia/<int:pk>', views.DetalleNoticiaF, name='detalle_noticia'),
    
    path('Listar', views.ListarNoticiasF, name="listar_noticias"),

    path('Detalle/<int:pk>', views.DetalleNoticiaF, name="detalle_noticias"),

    path('Filtro/<int:pk>', views.Filtro_Categoria, name="filtro_categoria"),

    path('Borrar/<int:pk>', views.BorrarNoticia.as_view(), name="borrar_noticia"),

    path('Modificar/<int:pk>', views.ModificarNoticia.as_view(), name="modificar_noticia"),
   
    path('categorias', views.Categorias, name='categorias'),

    
   
   

]

proyectofinal/proyectofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name = 'home'),
    path('sobre-nosotros', views.SobreNosotros, name = 'sobre-nosotros'),
    path('contacto', views.Contacto, name = 'contacto'),

    #URLS DE AUTH
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    #URLS DE USUARIOS
    path('usuarios/', include('apps.usuarios.urls')),
    #URLS DE NOTICIAS
    path('noticias/', include('apps.noticias.urls')),
    # NOTICIAS ORDENADAS SEGUN...
    path('ord-fecha-desc/', views.OrdFechaDesc, name="ord-fecha-desc"),
    path('ord-tit-asc/', views.OrdTitAsc, name="ord-tit-asc"),
    path('ord-tit-desc/', views.OrdTitDesc, name="ord-tit-desc"),

     #URLS DE COMENTARIOS
    path('comentarios/', include('apps.comentarios.urls')),
    
     #URLS categorias-objetivos
    path('Categorias_objetivos', views.Categorias_objetivos, name='categorias_objetivos'),
      #Trea los objetivos de la categoria seleccionada
    path('objetivos/<int:categoria_id>/', views.objetivos_por_categoria, name = 'objetivos_categoria'),
    # Trae todas las categorias para buscar los objtivos

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectofinal/apps/noticias/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
	nombre = models.CharField(max_length=80)
	imagen = models.ImageField(upload_to= 'categoria')

	def __str__(self):
		return self.nombre

class Objetivo(models.Model):
	Objetivos = models.TextField()
	categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
	
	def __str__(self):
		return self.Objetivos




class Noticia(models.Model):
	creado = models.DateTimeField(
		'creado',
		auto_now_add=True
	)
	modificado = models.DateTimeField(
		'modificado',
		auto_now=True
	)
	titulo = models.CharField(max_length = 250)
	descripcion = models.CharField(max_length= 400)
	contenido = models.TextField()
	autor = models.ForeignKey(User, on_delete = models.CASCADE)
	imagen = models.ImageField(upload_to = 'noticias')
	categoria = models.ManyToManyField(Categoria, blank=False)

	def MisComentarios(self):
		return self.comentario_set.all()

	def __str__(self):
		return self.titulo

proyectofinal/apps/noticias/forms.py
from django import forms
from .models import *



class Form_Alta(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ('titulo','descripcion','contenido', 'imagen', 'categoria')
        widgets = {
            'categoria': forms.CheckboxSelectMultiple(attrs={
                'class': 'form-check-input',
                'type': 'checkbox', 
                'value': '',
                'id':'defaultCheck1',
            })
        }



class Form_Modificacion(forms.ModelForm):

    class Meta:
        model = Noticia
        fields = ('contenido','imagen','categoria')
        categoria = forms.ModelMultipleChoiceField(
        queryset=Categoria.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
        

proyectofinal/apps/noticias/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView,DeleteView, UpdateView
from django.urls import reverse_lazy

from .models import Noticia,Categoria,Objetivo
from .forms import Form_Alta,Form_Modificacion
#CONTROLA SI EL USUARIO ESTA LOGEADO EN UNA VISTA BASADA EN CLASES
from django.contrib.auth.mixins import LoginRequiredMixin
#CONTROLA SI EL USUARIO ESTA LOGEADO EN UNA VISTA BASADA EN FUNCIONEs
from django.contrib.auth.decorators import login_required

#CONTROLA SI EL USUARIO ESTA LOGEADO
from django.contrib.auth.mixins import LoginRequiredMixin

class CrearNoticiaC(LoginRequiredMixin, CreateView):
	model = Noticia
	form_class = Form_Alta
	template_name = 'noticias/crear.html'
	success_url = reverse_lazy('noticias:listar_noticias')
	
	
	def form_valid(self, form):
		noticia = form.save(commit=False)
		noticia.autor = self.request.user
		return super(CrearNoticiaC, self).form_valid(form)


class ListarNoticias(ListView):
	model = Noticia
	template_name = 'noticias/listar.html'
	#POR DEFECTO ESTA VISTA MANDA AL TEMPLATE UNA VARIABLE
	#LLAMADA OBJECT_LIST, CON LA LISTA DE TODAS LAS NOTICIAS



@login_required
def ListarNoticiasF(request):
	ctx = {}
	todas_noticias = Noticia.objects.all()
	ctx['object_list'] = todas_noticias
	#ctx['nombre'] = 'Nicolas'
	return render(request, 'noticias/listar.html', ctx)

def DetalleNoticiaF(request, pk):
	ctx = {}
	noti = Noticia.objects.get(id = pk)
	ctx['noticia'] = noti
	return render(request, 'noticias/detalle.html', ctx)

#
#ctx = {'object_list': [lista de objectos], 'nombre':'Nicolas'}
# CUANDO EL HTML RECIBE EL DICCIONARIO CTX, AUTOMATICAMENTE LO DESARMA EN VARIABLES
# EN EL HTML
# object_list = [lista de objectos]
# nombre = 'Nicolas'

#ORM
# CONSULTA PARA TRAER TODOS LOS DATOS
# select * from Noticia  SQL
# Noticia.objects.all()   ORM

#CONSuLTA PARA TRAER SOLO UN DATO (POR CLAVE)
# select * from Noticia where id = algo
# Noticia.objects.get(id = algo)

#CONSuLTA PARA TRAER SOLO Algunos datos (POR filtro)
# select * from Noticia where categororia = deportes
# Noticia.objects.filter(categoria = deportes)

#class Categorias(ListView):
	#model = Categoria
	#template_name = 'noticias/categorias.html'




def Categorias(request):
    ctx = {}
    lista_cate = Categoria.objects.all()
    ctx['object_list'] = lista_cate
    return render(request, 'noticias/categorias.html', ctx)


		

def Filtro_Categoria(request, pk):
	ctx = {}
	cate = Categoria.objects.get(id = pk)
	filtadas = Noticia.objects.filter(categoria = cate)
	ctx['object_list'] = filtadas
	return render(request, 'noticias/categoria-lista.html', ctx)

class BorrarNoticia(DeleteView):
	model = Noticia
	success_url = reverse_lazy('noticias:listar_noticias')


def MisNoticias(request):
	ctx = {}
	lista_noticias = Noticia.objects.filter(autor = request.user)
	print(lista_noticias)
	ctx['object_list'] = lista_noticias

	return render(request, 'noticias/misNoticias.html', ctx)


class ModificarNoticia(UpdateView):
	model = Noticia
	form_class = Form_Modificacion
	template_name = 'noticias/Modificar.html'
	success_url = reverse_lazy('noticias/modificar.html')

proyectofinal/templates/noticias/categoria-lista.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

<div class="container text-bg-dark my-3">
	<div class="row">
        {% for categoria in object_list %}
			<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4 my-3">
				<h2 style="text-align: center;">{{ categoria.0 }}</h2>
				<img src="{{ categoria.1.url }}" class="card-img-top" alt="Imagen de la noticia" style="height: 150px; object-fit: contain;">
				<div class="card-body">
				 
				
				</div>
			</div>
		{% endfor %}
    </div>


    {% endblock contenido %}

proyectofinal/templates/noticias/categorias.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container m-3 p-2 text-bg-dark mx-auto">
    <div class="row">
        <h4 class="mb-3">Seleccione una categoria para ver los objetivos</h4>
        <hr class="mb-3">
    </div>
    <div class="row">
        {% for n in object_list %}
        <div class="card col-xs-12 col-sm-6 col-md-3 col-lg-2 bg-dark">
            <li>{{ categoria.nombre }}</li>
                <a href="{% url 'noticias:objetivos_categoria' n.pk %}" class="text-decoration-none">
                    <img class="img-cat d-block mx-auto" src="{{ n.imagen.url }}" alt="Imagen de la categoria">
                </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock contenido %}

proyectofinal/templates/noticias/crear.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}



{% block contenido %}

  
  <section class="vh-70 gradient-custom">
    <div class="container mt-2" style="background-color:gra; border-radius: 15px di;">
      <div class="row gutter-4">
        <div class="container-fluid col-9 px-4">
          <h2 style="color: rgb(0, 0, 0); padding-top: 20px;">Creacion de noticia</h2>
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.errors}} 
            <div class="form-outline form-white mb-5">
              <label style="color: rgb(0, 0, 0)" for="{{ form.titulo.id_for_label}}">Titulo</label>
              {{ form.titulo|add_class:"form-control mb-n1" }}
            <div class="form-outline form-white mb-5">
              <label style="color: rgb(0, 0, 0)" for="{{ form.descripcion.id_for_label}}">Descripcion</label>
              {{ form.descripcion|add_class:"form-control mb-n1" }}
            </div>
            </div>
            <div class="form-outline form-white mb-5">
              <label style="color: rgb(0, 0, 0)" for="{{ form.contenido.id_for_label }}">Contenido</label>
              {{ form.contenido|add_class:"form-control form-control-lg "}}
            </div>
            <div class="form-outline form-white mb-5">
              <label style="color: rgb(0, 0, 0)" for="{{ form.imagen.id_for_label }}">Imagen</label>
              {% render_field form.imagen class="search-label-icon" %}
            </div>
          </div>
          <div class=" container col-3">
            <div class="form-group">
              <h2 style="color: rgb(0, 0, 0); padding-top: 20px;">Categorias</h2>
              {% for c in form.categoria %}
              <div class="form-check ">
                  {{ c }}
                  
              </div>
              {% endfor %}
              
            </div>
          </div>
            <button style="background-color: blue;" class="btn btn-outline-light btn-lg px-5" type="submit">CREAR</button>
          </form>
            <a href="{% url 'home' %}" class="btn btn-outline-light btn-lg px-5 mb-n1">HOME</a>
        </div>
      </div>
    </div>
  </section>        
      
  {% endblock contenido %}
        

  
  
  
     

  

proyectofinal/templates/noticias/detalle.html
{% extends 'base.html' %}

{% block contenido %}

<div class="container text-bg-dark m-3 p-3 mx-auto">
    <a href="{% url 'home' %}">
      <i class="fa fa-solid fa-chevron-left btn btn-go" style="color: white; margin-right: 2rem;"></i>
    </a>
  <div class="text-center">
      <h1 class="fs-30 fw-bold">{{noticia.titulo}}</h1>
  <h4>{{noticia.descripcion}}</h4>
  </div>
  <h6>Fecha de publicacion: {{noticia.creado}}</h6>
  <h6>Autor: {{noticia.autor}}</h6>
  <div class="d-lg-flex">
    {% if noticia.categoria %}
    {% for n in noticia.categoria.all %}
    <a href="{% url 'noticias:filtro_categoria' n.pk %}" style="border-right: 1px solid #fff; color:#fff;" class=" text-decoration-none px-2 btn-categoria btn-categoria-{{n.pk}}">{{n.nombre}}</a>
    {% endfor %}
    {% endif %}
  </div>
  <hr>
  <img class="rounded mx-auto d-block" src="{{noticia.imagen.url}}" alt="Imagen de la noticia" width="400px">
  <p class="mx-auto w-75 pt-3">{{noticia.contenido}}</p>
  <p class="italic">Ultima modificacion: {{noticia.modificado}}</p>
  <div class="d-flex justify-content-end">
    <a href="{% url 'noticias:modificar_noticia' noticia.pk %}" class="btn btn-go mx-4"><i class="fa fa-regular fa-feather"></i></a>
            <a href="{% url 'noticias:borrar_noticia' noticia.pk %}" class="btn btn-go me-4"><i class="fa fa-solid fa-trash"></i></a>
  </div>
  <hr>
	</div>
	<h4 style="color: aliceblue;">Comentar</h4>
	<div class="row" class="mb-3">
		<div class="container">
			{% if user.is_authenticated %}
			<form method="POST" action="{% url 'comentarios:agregar_comentarios' noticia.pk %}">{%csrf_token%}
				<textarea class="col-12" type="text" name="comentario"></textarea>
					<input class="btn-go btn" type="submit" name="" value="Guardar">
			</form>
		</div>
			{% endif %}
		
</div>


</div>

<div class="container">
    <div class="row">
        <div class="panel panel-default widget">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-comment"></span>
                <h3 style="color: blueviolet;" class="panel-title">
                    Comentarios recientes</h3>
                <span class="label label-info">
                    78</span>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    {% for c in noticia.MisComentarios %}
					<li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-2 col-md-1">
                                <img src="http://placehold.it/80" class="img-circle img-responsive" alt="" /></div>
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <a href="http://www.jquery2dotnet.com/2013/10/google-style-login-page-desing-usign.html">
                                        Google Style Login Page Design Using Bootstrap</a>
                                    <div class="mic-info">
                                        By: <a href="#">{{c.usuario}}</a> on {{c.creado}}
                                    </div>
                                </div>
                                <div class="comment-text">
                                    {{c.texto}}
                                </div>
                                <div class="action">
                                    <button type="button" class="btn btn-primary btn-xs">
                                        <span class="glyphicon glyphicon-pencil">Editar</span>
                                    </button>
                                    <button type="button" class="btn btn-success btn-xs" title="Approved">
                                        <span class="glyphicon glyphicon-ok"></span>
                                    </button>
                                    <button type="button" class="btn btn-danger btn-xs" title="Delete">
                                        <span class="glyphicon glyphicon-trash">Borrar</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </li>
					{%endfor%}
                    
                <a href="#" class="btn btn-primary btn-sm btn-block" role="button"><span class="glyphicon glyphicon-refresh"></span> More</a>
            </div>
        </div>
    </div>

	{% endblock contenido %}

proyectofinal/templates/noticias/listar.html
{% extends 'base.html' %}

{% block contenido %}
{% for n in object_list %}
	<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4" style="text-align: center;image-rendering: crisp-edges;">
		<div style="text-align: center;">
            <img src="{{n.imagen.url}}" width="200">
        </div>
        
		<div class="card-body">
		  <h5 class="card-title">{{n.titulo}}</h5>
		  <p class="card-text">comentario</p>
		  <a href="{% url 'noticias:detalle_noticias' n.pk %}" class="btn btn-primary">Leer más</a>
		</div>
        
    </div>
		{% endfor %}
{% endblock contenido %}

proyectofinal/templates/noticias/misNoticias.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

<div class="container text-bg-dark my-3">
    <div class="row">
            <a class="col-lg-12 btn-go btn" href="{% url 'noticias:crear_noticia' %}" class="btn-go btn">Crear una noticia</a>
        
    </div>
    <div class="row">
        {% for n in object_list %}
			<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4 my-3">
				<img src="{{n.imagen.url}}" class="card-img-top" alt="Imagen de la noticia" style="height: 150px; object-fit: contain;">
				<div class="card-body">
				  <h5 class="card-title">{{n.titulo}}</h5>
				  <p class="card-text">{{n.descripcion}}</p>
				  <a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer mas</a>
				  <a href="{% url 'noticias:modificar_noticia' n.pk %}" class="btn btn-go"><i class="fa fa-regular fa-feather"></i></a>
				  <a href="{% url 'noticias:borrar_noticia' n.pk %}" class="btn btn-go"><i class="fa fa-solid fa-trash"></i></a>
				</div>
			</div>
		{% endfor %}
    </div>
</div>

{% endblock contenido %}

proyectofinal/templates/noticias/modificar.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}         
         <h3 class="mb-4">MODIFICAR LA NOTICIA: "{{object.titulo}}"</h3>
          {{form.as_p}}
          <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock contenido %}

proyectofinal/templates/noticias/mostrar_articulos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>INFO 2023 Noticias</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        {% for n in object_list %}
        <header class="masthead" style="background-image: url('{{n.imagen.url}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{n.titulo}}</h1>
                            <h2 class="subheading"></h2>
                            <span class="meta">
                                Posteado por
                                <a href="#!">AUTOR: {{n.autor}}</a>
                                FECHA: {{n.creado}}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>{{n.contenido}}</p>
                            Linsk?
                            <a href="http://spaceipsum.com/">LINK</a>
                            &middot; Images sacadas de?
                            <a href="https://www.flickr.com/photos/nasacommons/">LINK</a>
                            
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </article>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

proyectofinal/templates/noticias/noticia_confirm_delete.html
{% extends 'base.html' %}

{% block contenido %}
	
	<form method="post">{% csrf_token %}
    	<p>Estas seguro que desa eliminar: "{{ object }}"?</p>
	    {{ form }}
	    <input type="submit" value="CONFIRMAR">
	</form>

{% endblock contenido %}

proyectofinal/templates/noticias/noticiasPorCat.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container m-3 text-bg-dark mx-auto">
    <div class="row m-2">
        <h2>{{nom_cat.nombre}}</h2>
        <hr>
    </div>
    <div class="row">
        {% for n in noticia %}
        <div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4 my-3">
            <img src="{{n.imagen.url}}" class="card-img-top" alt="Imagen de la noticia" style="height: 150px; object-fit: contain;">
            <div class="card-body">
              <h5 class="card-title">{{n.titulo}}</h5>
              <p class="card-text">{{n.descripcion}}</p>
              <a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer mas</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock contenido %}