ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Inicio, name='inicio'),
    path('sobre-nosotros', views.SobreNosotros, name = 'sobre-nosotros'),
    path('contacto', views.Contacto, name = 'contacto'),

    # NOTICIAS ORDENADAS SEGUN...
    path('ord-fecha-desc/', views.OrdFechaDesc, name="ord-fecha-desc"),
    path('ord-tit-asc/', views.OrdTitAsc, name="ord-tit-asc"),
    path('ord-tit-desc/', views.OrdTitDesc, name="ord-tit-desc"),

    # URLS DE AUTH
    path('login/', auth.LoginView.as_view(template_name="usuarios/login.html"), name='login'),
    path('logout/', auth.LogoutView.as_view(), name='logout'),

    # URLS USUARIOS
    path('usuarios/', include('apps.usuarios.urls')),

    # URLS NOTICIAS
    path('noticias/', include('apps.noticias.urls')),

    # URLS COMENTARIOS
    path('comentarios/', include('apps.comentarios.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/apps/comentarios/urls.py
from django.urls import path
from . import views

app_name = 'comentarios'

urlpatterns = [
    # Agregar comentario
    path('agregar-com/<int:pk>', views.Agregar, name='agregar_comentarios'),

    # Modificar comentario
    path('borrar-comentario/<int:pk>', views.BorrarComentario.as_view(), name="borrar_comentario"),

    # Borrar comentario
    path('modificar-comentario/<int:pk>', views.ModificarComentario.as_view(), name="modificar_comentario"),

    # Seccion mis comentarios
    path('mis-comentarios', views.MisComentarios, name='misComentarios'),

]

ProyectoFinal/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    # Ver categorias
    path('categorias', views.Categorias, name="categorias"),

    # Crear una noticia
    path('crearNoticia', views.CrearNoticia.as_view(), name = 'crearNoticia'),

    # Noticias del usuario 
    path('mis-noticias', views.MisNoticias, name="misNoticias"),

    # Listar noticias
    path('listar-noticias', views.ListarNoticias, name='listar_noticias'),

    # Borrar una noticia
    path('borrar-noticia/<int:pk>', views.BorrarNoticia.as_view(), name="borrar_noticia"),

    # Actualizar una noticia
    path('modificar-noticia/<int:pk>', views.ModificarNoticia.as_view(), name="modificar_noticia"),

    # Detalle de una noticia
    path('detalle-noticia/<int:pk>', views.DetalleNoticia, name='detalle_noticia'),

    # Noticias por categoria
    path('not-categoria/<int:pk>', views.NoticiasPorCategoria, name='not_categoria'),
]

ProyectoFinal/apps/comentarios/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.noticias.models import Noticia

class Comentario(models.Model):
	creado = models.DateTimeField(
		'creado',
		auto_now_add=True
	)
	modificado = models.DateTimeField(
		'modificado',
		auto_now=True
	)
	texto = models.TextField(max_length = 1000)
	usuario = models.ForeignKey(User, on_delete = models.CASCADE)
	noticia = models.ForeignKey(Noticia, on_delete = models.CASCADE)

	def __str__(self):
		return f"{self.usuario}-{self.noticia}"

ProyectoFinal/apps/noticias/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
	nombre = models.CharField(max_length=80)
	imagen_cat = models.ImageField(upload_to = 'categorias', default='https://www.un.org/sustainabledevelopment/wp-content/uploads/sites/3/2017/12/04-11-2017-IFAD-35822.jpg')

	def __str__(self):
		return self.nombre

#########################################################################

class Noticia(models.Model):
	creado = models.DateTimeField(
		'creado',
		auto_now_add=True
	)
	modificado = models.DateTimeField(
		'modificado',
		auto_now=True
	)
	titulo = models.CharField(max_length = 250)
	descripcion = models.CharField(max_length= 400)
	contenido = models.TextField()
	autor = models.ForeignKey(User, on_delete = models.CASCADE)
	imagen = models.ImageField(upload_to = 'noticias')
	categoria = models.ManyToManyField(Categoria, blank=False)

	def __str__(self):
		return self.titulo

ProyectoFinal/apps/noticias/forms.py
from django import forms
from .models import Noticia, Categoria


class Form_Alta(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ('titulo', 'descripcion', 'contenido', 'imagen', 'categoria')
        widgets = {
            'categoria': forms.CheckboxSelectMultiple(attrs={
                'class': 'form-check-input',
                'type': 'checkbox', 
                'value': '',
                'id':'defaultCheck1',
            }),
             
        }


class Form_Modificacion(forms.ModelForm):

    class Meta:
        model = Noticia
        fields = ('titulo', 'descripcion', 'contenido', 'imagen', 'categoria')
        widgets = {
            'categoria': forms.CheckboxSelectMultiple(attrs={
                'class': 'form-check-input',
                'type': 'checkbox', 
                'value': '',
                'id':'defaultCheck1',
            })
        }

ProyectoFinal/apps/noticias/views.py
from django.shortcuts import render
from .models import Categoria, Noticia
from apps.comentarios.models import Comentario
from .forms import *
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

#CONTROLA SI EL USUARIO ESTA LOGEADO
from django.contrib.auth.mixins import LoginRequiredMixin

#Permisos de colaborador
from django.contrib.auth.mixins import PermissionRequiredMixin

#Handler de errores
from django.core.exceptions import PermissionDenied
# Create your views here.

def Categorias(request):
    ctx = {}

    objetos_categorias = Categoria.objects.all()

    ctx['object_list'] = objetos_categorias

    return render(request, 'noticias/categorias.html', ctx)



# class CrearNoticia(PermissionRequiredMixin, CreateView):
class CrearNoticia( CreateView):
	model = Noticia
	form_class = Form_Alta
	template_name = 'noticias/crearNoticia.html'
	success_url = reverse_lazy('noticias:misNoticias')
	permission_required = 'noticias.add_noticia'

	def form_valid(self, form):
		noticia = form.save(commit=False)
		noticia.autor = self.request.user
		return super(CrearNoticia, self).form_valid(form)
	
    
def MisNoticias(request):
	ctx = {}
	lista_noticias = Noticia.objects.filter(autor = request.user).order_by('-creado')
	print(lista_noticias)
	ctx['object_list'] = lista_noticias

	return render(request, 'noticias/misNoticias.html', ctx)


def ListarNoticias(request):
	ctx = {}
	categorias = Categoria.objects.all()
	#CAPUTRAR PARAMETROS
	todas_noticias = Noticia.objects.all()
	orden = request.GET.get('orden',None)
	if orden:
		if orden == 'titulo_desc':
			todas_noticias = todas_noticias.order_by('-titulo')
		elif orden == 'titulo_asc':
			todas_noticias = todas_noticias.order_by('titulo')
		elif orden == 'noti_nuevas':
			todas_noticias = todas_noticias.order_by('-creado')
		elif orden == 'noti_viejas':
			todas_noticias = todas_noticias.order_by('creado')

	ctx['object_list'] = todas_noticias
	return render(request, 'noticias/listarNoticias.html', ctx)



class BorrarNoticia(PermissionRequiredMixin,DeleteView):
	model = Noticia
	success_url = reverse_lazy('noticias:misNoticias')
	permission_required = 'noticias.delete_noticia'
	permission_denied_message = 'NO ESTAS AUTORIZADO PARA REALIZAR CAMBIOS '

#probando permisos de colaborador para editar 

class ModificarNoticia(PermissionRequiredMixin,UpdateView):
	model = Noticia
	form_class = Form_Modificacion
	template_name = 'noticias/modificar.html'
	success_url = reverse_lazy('noticias:misNoticias')
	permission_required = 'noticias.change_noticia'
	permission_denied_message = 'NO ESTAS AUTORIZADO PARA REALIZAR CAMBIOS'
	

def DetalleNoticia(request, pk):
	ctx = {}
	mis_com = []

	detalle_noticia = Noticia.objects.get(id = pk)
	comentarios = Comentario.objects.filter(noticia = pk).order_by('-creado')
	
	ctx['detalle'] = detalle_noticia
	ctx['lista_comentarios'] = comentarios

	return render(request, 'noticias/detalle.html', ctx)


def NoticiasPorCategoria(request, pk):
	# pk de la categoria
	ctx = {}
	orden = request.GET.get('orden',None)
	noticias = Noticia.objects.filter(categoria = pk)
	categoria = Categoria.objects.get(id = pk)
	if orden:
		if orden == 'titulo_desc':
			noticias = noticias.order_by('-titulo')
		elif orden == 'titulo_asc':
			noticias = noticias.order_by('titulo')
		elif orden == 'noti_nuevas':
			noticias = noticias.order_by('-creado')
		elif orden == 'noti_viejas':
			noticias = noticias.order_by('creado')

	ctx['noticia'] = noticias
	ctx['nom_cat'] = categoria

	return render(request, 'noticias/noticiasPorCat.html', ctx)
	

ProyectoFinal/templates/noticias/categorias.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container m-3 p-2 text-bg-dark mx-auto">
    <div class="row">
        <h4 class="">Seleccione una categoria para ver noticias relacionadas</h4>
    </div>
    <hr class="mb-3">
    <div class="row">
        <a href="https://www.argentina.gob.ar/politicassociales/ods/institucional/17objetivos" target="_blank" class="text-decoration-none text-light mb-3">Para conocer mas sobre los objetivos - - > </a>
        {% for n in object_list %}
        <div class="card col-xs-12 col-sm-6 col-md-3 col-lg-2 bg-dark">
            <a href="{% url 'noticias:not_categoria' n.pk %}" class="text-decoration-none">
                <img class="img-cat d-block mx-auto" src="{{n.imagen_cat.url}}" alt="Imagen de la categoria">
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock contenido %}

ProyectoFinal/templates/noticias/crearNoticia.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block contenido %}

  
<div class="container m-3 mx-auto py-2 px-3 text-bg-dark">
    <div class="d-lg-flex gap-5">
        <div class="mx-auto w-lg-50">
          <h2 class="pt-2" style="color: #999;">Creacion de noticia</h2>
          <hr>
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.errors}} 
            <div class="form-outline form-white mb-3">
              <label class="p-1" for="{{ form.titulo.id_for_label}}">Titulo</label>
              {{ form.titulo|add_class:"form-control mb-n1" }}
            </div>
            <div class="form-outline form-white mb-3">
              <label class="p-1" for="{{ form.descripcion.id_for_label}}">Descripcion</label>
              {{ form.descripcion|add_class:"form-control mb-n1" }}
            </div>
            <div class="form-outline form-white mb-3">
              <label class="p-1" for="{{ form.contenido.id_for_label }}">Contenido</label>
              {{ form.contenido|add_class:"form-control form-control-lg "}}
            </div>
            <div class="form-outline form-white mb-3">
              <label class="p-1" for="{{ form.imagen.id_for_label }}">Imagen</label>
              {% render_field form.imagen class="search-label-icon" %}
            </div>         
          
        </div>
        <div class="mx-auto w-lg-50">
            <div class="form-group">
              <h2 class="pt-3" style="color: #999;">Categorias</h2>
              <hr>
              {% for c in form.categoria %}
                <div class="text-light form-check">
                    {{ c }}  
                </div>
              {% endfor %}
              
            </div>
        </div>
            
    </div> 
    <button class="btn btn-go mt-3 d-block w-100" type="submit">CREAR</button> 
  </form>
</div>     
  
  {% endblock contenido %}
        

  

ProyectoFinal/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

  <div class="container text-bg-dark m-3 p-3 mx-auto">
          <!-- <a href="{% url 'inicio' %}">
            <i class="fa fa-solid fa-chevron-left btn btn-go" style="color: white; margin-right: 2rem;"></i>
          </a> -->
          <div class="text-center">
              <h1 class="fs-30 fw-bold">{{detalle.titulo}}</h1>
          <h4 style="color: #aaa;">{{detalle.descripcion}}</h4>
          </div>
        <h6>Fecha de publicacion: {{detalle.creado}}</h6>
        <h6>Autor: {{detalle.autor}}</h6>
          <div class="d-lg-flex">
            {% if detalle.categoria %}
            {% for n in detalle.categoria.all %}
            <a href="{% url 'noticias:not_categoria' n.pk %}" style="border-right: 1px solid #fff; color:#fff;" class=" text-decoration-none px-2 btn-categoria btn-categoria-{{n.pk}}">{{n.nombre}}</a>
            {% endfor %}
            {% endif %}
          </div>
        <hr>
        <img class="rounded mx-auto d-block" src="{{detalle.imagen.url}}" alt="Imagen de la noticia" width="400px">
        <p class="mx-auto w-75 pt-3">{{detalle.contenido}}</p>
        <p class="italic">Ultima modificacion: {{detalle.modificado}}</p>
        
          <div class="d-flex justify-content-end">
            {% if perms.noticias.change_noticia%}
            <a href="{% url 'noticias:modificar_noticia' detalle.pk %}" class="btn btn-go mx-4"><i class="fa fa-regular fa-feather"></i></a>
            {% endif%}
            {% if perms.noticias.delete_noticia%}
            <a href="{% url 'noticias:borrar_noticia' detalle.pk %}" class="btn btn-go me-4"><i class="fa fa-solid fa-trash"></i></a>
            {% endif%} 
          </div>
          
        <hr>
        <h4>COMENTARIOS</h4>
        <div class="row" class="mb-3">
          {% if user.is_authenticated %}
              <form class="m-1" method="POST" action="{% url 'comentarios:agregar_comentarios' detalle.pk %}">{%csrf_token%}

                <textarea class="col-12" type="text" name="comentario">

                </textarea>
                <input class="btn-go btn mb-3" type="submit" name="" value="Guardar">
              </form>
              <hr>
          {% endif %}
          
          {% for n in lista_comentarios %}
          <div>
            <h4>{{n.usuario}}</h4>
            <p>{{n.texto}}</p>
            <p>{{n.creado}}</p>
            <div class="mb-2">
              {% if perms.comentarios.change_comentario or user == n.usuario %} 
              <a href="{% url 'comentarios:modificar_comentario' n.pk %}" class="btn btn-go"><i class="fa fa-regular fa-feather"></i></a>
              {% endif %}
              {% if perms.comentarios.delete_comentario or user == n.usuario %}
				      <a href="{% url 'comentarios:borrar_comentario' n.pk %}" class="btn btn-go"><i class="fa fa-solid fa-trash"></i></a>
            </div>
              {% endif %}
          </div>
          <hr>
          {% endfor %}
          </div>
  </div>
</div>

{% endblock contenido %}

ProyectoFinal/templates/noticias/listarNoticias.html
{% extends 'base.html' %}

{% block contenido %}

<div class="container text-bg-dark my-3">
    <div class="row">
		<div class="container" style="text-align: center; padding-top: 20px;padding-bottom: 20px;">
			<h4 style="color:  white;padding-bottom: 10px;">Ordenar por</h4>
			<button style="color:white;" class="btn btn-go mx-2 mb-2" onclick="window.location.href='?orden=titulo_desc'">Titulo Desc</button>
			<button style="color:white;" class="btn btn-go mx-2 mb-2" onclick="window.location.href='?orden=titulo_asc'" >Titulo Asc</button>
			<button style="color:white;" class="btn btn-go mx-2 mb-2" onclick="window.location.href='?orden=noti_nuevas'" >Mas Nuevos</button>
			<button style="color:white;" class="btn btn-go mx-2 mb-2" onclick="window.location.href='?orden=noti_viejas'" >Mas Antiguos</button>
	</div>
	{% for n in object_list %}
		<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4 my-3">
			<img src="{{n.imagen.url}}" class="card-img-top" alt="Imagen de la noticia" style="height: 150px; object-fit: contain;">
			<div class="card-body">
			<h5 class="card-title">{{n.titulo}}</h5>
			<p class="card-text">{{n.descripcion|truncatechars:150}}</p>
			<p><em>{{n.creado}}</em></p>
			<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer mas</a>
			
			<a href="{% url 'noticias:modificar_noticia' n.pk %}" class="btn btn-go"><i class="fa fa-regular fa-feather"></i></a>
			<a href="{% url 'noticias:borrar_noticia' n.pk %}" class="btn btn-go"><i class="fa fa-solid fa-trash"></i></a>
			</div>
		</div>
	{% endfor %}
</div>
</div>

{% endblock contenido %}

ProyectoFinal/templates/noticias/misNoticias.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

<div class="container text-bg-dark my-3">
	{% if perms.noticias.add_noticia %}
    <div class="row">
            <a class="col-lg-12 btn-go btn" href="{% url 'noticias:crearNoticia' %}" class="btn-go btn">Crear una noticia</a>
    {% endif %}    
    </div>
    <div class="row">
        {% for n in object_list %}
			<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4 my-3">
				<img src="{{n.imagen.url}}" class="card-img-top" alt="Imagen de la noticia" style="height: 150px; object-fit: contain;">
				<div class="card-body">
				  <h5 class="card-title">{{n.titulo}}</h5>
				  <div class="d-flex pb-2">
					{% for cat in n.categoria.all %}
					<div class="btn-categoria-{{cat.pk}}" style="width: 15px; height: 10px;" title="{{cat.nombre}}"></div>
					{% endfor %}
					</div>
				  <a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer mas</a>
				  <a href="{% url 'noticias:modificar_noticia' n.pk %}" class="btn btn-go"><i class="fa fa-regular fa-feather"></i></a>
				  <a href="{% url 'noticias:borrar_noticia' n.pk %}" class="btn btn-go"><i class="fa fa-solid fa-trash"></i></a>
				</div>
			</div>
		{% endfor %}
    </div>
</div>

{% endblock contenido %}

ProyectoFinal/templates/noticias/modificar.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block contenido %}

  
<div class="container m-3 mx-auto py-2 px-3 text-bg-dark">
    <div class="d-lg-flex gap-5">
        <div class="mx-auto w-lg-50">
          <h2 class="pt-2" style="color: #999;">Modficar la noticia</h2>
          <hr>
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.errors}} 
            <div class="form-outline form-white mb-3">
              <label class="p-1" for="{{ form.titulo.id_for_label}}">Titulo</label>
              {{ form.titulo|add_class:"form-control mb-n1" }}
            </div>
            <div class="form-outline form-white mb-3">
              <label class="p-1" for="{{ form.descripcion.id_for_label}}">Descripcion</label>
              {{ form.descripcion|add_class:"form-control mb-n1" }}
            </div>
            <div class="form-outline form-white mb-3">
              <label class="p-1" for="{{ form.contenido.id_for_label }}">Contenido</label>
              {{ form.contenido|add_class:"form-control form-control-lg "}}
            </div>
            <div class="form-outline form-white mb-3">
              <label class="p-1" for="{{ form.imagen.id_for_label }}">Imagen</label>
              {% render_field form.imagen class="search-label-icon" %}
            </div>         
          
        </div>
        <div class="mx-auto w-lg-50">
            <div class="form-group">
              <h2 class="pt-3" style="color: #999;">Categorias</h2>
              <hr>
              {% for c in form.categoria %}
                <div class="text-light form-check">
                    {{ c }}  
                </div>
              {% endfor %}
              
            </div>
        </div>
            
    </div> 
    <button class="btn btn-go mt-3 d-block w-100" type="submit">Guardar cambios</button> 
  </form>
</div>     
  
  {% endblock contenido %}

ProyectoFinal/templates/noticias/noticia_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container text-bg-dark text-center">
	<div class="row">
	<form method="post">{% csrf_token %}
    	<p>Estas seguro que desa eliminar: "{{ object }}"?</p>
	    {{ form }}
	    <input class="btn-go btn" type="submit" value="Confirmar">
		
	<!-- <input class="btn-go btn" value="Cancelar"> -->
	</form>
	</div>
</div>
{% endblock contenido %}

ProyectoFinal/templates/noticias/noticiasPorCat.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container" style="text-align: center; padding-top: 20px;">
    <h4 style="color: white;padding-bottom: 10px;">Ordenar por</h4>
    <button style="color:white;" class="btn btn-go mx-2 mb-2" onclick="window.location.href='?orden=titulo_desc'">Titulo Desc</button>
    <button style="color:white;" class="btn btn-go mb-2 mb-2" onclick="window.location.href='?orden=titulo_asc'" >Titulo Asc</button>
    <button style="color:white;" class="btn btn-go mx-2 mb-2" onclick="window.location.href='?orden=noti_nuevas'" >Mas Nuevos</button>
    <button style="color:white;" class="btn btn-go mx.2 mb-2" onclick="window.location.href='?orden=noti_viejas'" >Mas Antiguos</button>
</div>
<div class="container m-3 py-2 px-3 text-bg-dark mx-auto">
    <div class="row m-2">
        <h2 >{{nom_cat.nombre}}</h2>
        <hr>
    </div>
    <div class="row m-2">
        {% for n in noticia %}
        <div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4 my-3">
            <img src="{{n.imagen.url}}" class="card-img-top" alt="Imagen de la noticia" style="height: 150px; object-fit: contain;">
            <div class="card-body">
              <h5 class="card-title">{{n.titulo}}</h5>
              <a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer mas</a>
              <p><em>{{n.creado}}</em></p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock contenido %}