ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Inicio, name='inicio'),
    path('sobre-nosotros', views.SobreNosotros, name = 'sobre-nosotros'),
    path('contacto', views.Contacto, name = 'contacto'),

    # NOTICIAS ORDENADAS SEGUN...
    path('ord-fecha-desc/', views.OrdFechaDesc, name="ord-fecha-desc"),
    path('ord-tit-asc/', views.OrdTitAsc, name="ord-tit-asc"),
    path('ord-tit-desc/', views.OrdTitDesc, name="ord-tit-desc"),

    # URLS DE AUTH
    path('login/', auth.LoginView.as_view(template_name="usuarios/login.html"), name='login'),
    path('logout/', auth.LogoutView.as_view(), name='logout'),

    # URLS USUARIOS
    path('usuarios/', include('apps.usuarios.urls')),

    # URLS NOTICIAS
    path('noticias/', include('apps.noticias.urls')),

    # URLS COMENTARIOS
    path('comentarios/', include('apps.comentarios.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/apps/comentarios/urls.py
from django.urls import path
from . import views

app_name = 'comentarios'

urlpatterns = [
    # Agregar comentario
    path('agregar-com/<int:pk>', views.Agregar, name='agregar_comentarios'),

    # Modificar comentario
    path('borrar-comentario/<int:pk>', views.BorrarComentario.as_view(), name="borrar_comentario"),

    # Borrar comentario
    path('modificar-comentario/<int:pk>', views.ModificarComentario.as_view(), name="modificar_comentario"),

    # Seccion mis comentarios
    path('mis-comentarios', views.MisComentarios, name='misComentarios'),

]

ProyectoFinal/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    # Ver categorias
    path('categorias', views.Categorias, name="categorias"),

    # Crear una noticia
    path('crearNoticia', views.CrearNoticia.as_view(), name = 'crearNoticia'),

    # Noticias del usuario 
    path('mis-noticias', views.MisNoticias, name="misNoticias"),

    # Listar noticias
    path('listar-noticias', views.ListarNoticias, name='listar_noticias'),

    # Borrar una noticia
    path('borrar-noticia/<int:pk>', views.BorrarNoticia.as_view(), name="borrar_noticia"),

    # Actualizar una noticia
    path('modificar-noticia/<int:pk>', views.ModificarNoticia.as_view(), name="modificar_noticia"),

    # Detalle de una noticia
    path('detalle-noticia/<int:pk>', views.DetalleNoticia, name='detalle_noticia'),

    # Noticias por categoria
    path('not-categoria/<int:pk>', views.NoticiasPorCategoria, name='not_categoria'),
]

ProyectoFinal/apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('registro', views.Registro.as_view(), name = 'registro'),
]

ProyectoFinal/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- FONTAWESOME -->
    <script src="https://kit.fontawesome.com/b1758b74ef.js" crossorigin="anonymous"></script>

    <!-- STYLES -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <!-- FAVICON -->
    <link rel="shortcut icon" href="{% static 'img/slack.png' %}">

  </head>
  <body>
    <!-- HEADER -->
    <div class="header">
      <div class="container">
        <nav class="navbar navbar-expand-lg">
          <a class="navbar-brand" href="{% url 'inicio' %}"><i class="fa fa-brands fa-slack fs-4 fw-bold"></i></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link fs-6" aria-current="page" href="{% url 'inicio' %}" style="color: #bbb;">Home</a>
              </li>
              {% if user.is_staff %}
              <li class="nav-item">
                <a class="nav-link fs-6" href="{% url 'noticias:misNoticias' %}" style="color: #bbb;">Mis noticias</a>
              </li>
              {% endif %}
              {% if user.is_authenticated %}
              <li class="nav-item">
                
                <a class="nav-link fs-6" href="{% url 'comentarios:misComentarios' %}" style="color: #bbb;">Mis comentarios</a>
              </li>
              {% endif%}
              
              <li class="nav-item">
                <a class="nav-link fs-6" href="{% url 'sobre-nosotros' %}" style="color: #bbb;">Sobre nosotros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fs-6" href="{% url 'contacto' %}" style="color: #bbb;">Contacto</a>
              </li>
            </ul>
            <div class="d-flex gap-3 mt-3 mb-2">
              {% if user.is_authenticated %}
              <p class="fs-6 text-decoration-none log" style="color: #bbb;"> Usuario: {{ user.get_username }} </p>
              <a href="{% url 'logout' %}" class="fs-6 text-decoration-none log" style="color: #bbb;">Cerrar Sesion</a>
              {% else %}
              <a href="{% url 'login' %}" class="fs-6 text-decoration-none log" style="color: #bbb;">Iniciar sesión</a>
              <a href="{% url 'usuarios:registro' %}" class="fs-6 text-decoration-none log" style="color: #bbb;">Registrarse</a>
              {% endif %}
            </div>
          </div>
        </nav>
      </div>
    </div>
    

    

    <!-- SECTION -->
    {% block contenido %}

    {% endblock contenido %}


    <!-- FOOTER -->
    <div class="footer mt-3">
      <div class="container text-center ">
        <div class="row">
          <div class="col-12 mb-3 mt-3">
            <img src="{% static 'img/slack.svg' %}" alt="" width="70px">
          </div>
          <div class="col-8 offset-sm-2 mb-3 fs-6">
            <p>Somos estudiantes de la 2da etapa ''Desarrollo Web'' del Informatorio. Conformamos un equipo de desarrollo de 5 integrantes, trabajando en conjunto y de manera remota.</p>
          </div>
          <div class="col-12 mb-4">
            <a href="#" class="mx-3"><i class="fa fa-brands fa-youtube icon"></i></a>
            <a href="#" class="mx-3"><i class="fa fa-brands fa-github icon"></i></a>
            <a href="#" class="mx-3"><i class="fa fa-brands fa-envelope icon"></i></a>
            <a href="#" class="mx-3"><i class="fa fa-brands fa-linkedin icon"></i></a>
          </div>
          <div class="copyright col-12 mb-3">
            <h6>Copyright ©2023 All rights reserved | This template was made by <em>Grupo-2</em></h6>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    
  </body>
</html>

ProyectoFinal/templates/contacto.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container p-3 text-bg-dark m-3 mx-auto">
    <div class="d-lg-flex gap-2 align-items-center">
        <div class="text-center mx-auto">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14163.203087721158!2d-58.99416278730096!3d-27.444319015623673!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94450c5f32887753%3A0xf1624bc106f8101f!2sMinisterio%20de%20Trabajo%2C%20Empleo%20y%20Seguridad%20Social!5e0!3m2!1ses!2sar!4v1690121237439!5m2!1ses!2sar" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
        <div class="text-center mx-auto">
            <h5 class="text-center my-4 fs-4" >Más sobre este proyecto</h5>
            <div class="col-12 mb-4" >
                <a href="#" class="mx-3"><i class="fa fa-brands fa-youtube icon2"></i></a>
                <a href="#" class="mx-3"><i class="fa fa-brands fa-github icon2"></i></a>
                <a href="#" class="mx-3"><i class="fa fa-brands fa-envelope icon2"></i></a>
                <a href="#" class="mx-3"><i class="fa fa-brands fa-linkedin icon2"></i></a>
              </div>
              <h5 class="text-center mt-4 mb-2 fs-4" >Links de interes</h5>
              <ul class="text-center list-unstyled">
                <li class=""><a class="text-light d-block py-2 links-interes" href="https://www.un.org/sustainabledevelopment/es/objetivos-de-desarrollo-sostenible/">Naciones Unidas</a></li>
                <li class=""><a class="text-light d-block py-2 links-interes" href="https://www.cepal.org/es/temas/agenda-2030-desarrollo-sostenible/objetivos-desarrollo-sostenible-ods">Objetivos ODS 2030</a></li>
                <li class=""><a class="text-light d-block py-2 links-interes" href="https://www.un.org/sustainabledevelopment/es/development-agenda/">Agenda del DS</a></li>
                <li class=""><a class="text-light d-block py-2 links-interes" href="https://www.un.org/sustainabledevelopment/es/progress-report/">Informes sobre progresos</a></li>
              </ul>
        </div>
    </div>
    <div class="row">
        <div class="section mt-3 text-bg-dark col-sm-12 offset-sm-0">
            <h3 class="pt-3">Contáctanos</h3>
            <hr>
            <form action="https://formspree.io/f/mnqkjqvn" method="post" name="contacto" id ="contacto" >
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="floatingName" placeholder="Nombre" name="nombre">
                <label for="floatingName">Nombre</label>
            </div>

            <div class="form-floating mb-3">
                <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" name="email">
                <label for="floatingInput">Email</label>
            </div>

            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="floatingAsunto" placeholder="Asunto" name="asunto-cliente">
                <label for="floatingAsunto">Asunto</label>
            </div>

            <div class="form-floating mb-3">
                <textarea class="form-control" placeholder="Comentario" id="floatingTextarea" name="comentario"></textarea>
                <label for="floatingTextarea">Comentario</label>
            </div>
            <button type="submit" class="btn btn-go mx-auto d-block px-3 mb-3">Enviar</button>
        </form>
        </div>
        
    </div>
</div>
{% endblock contenido %}

ProyectoFinal/templates/inicio.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container ">
		
	<div class="dropdown my-2">
		<button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
			<i class="fa fa-solid fa-filter"></i>
		</button>
		<ul class="dropdown-menu bg-dark text-light">
			<li><a class="dropdown-item bg-dark text-light" href="{% url 'noticias:listar_noticias' %}">Todas las noticias</a></li>
			<li><a class="dropdown-item bg-dark text-light" href="{% url 'noticias:categorias' %}">Categorias</a></li>
		  	<li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-fecha-desc' %}">Primeras noticias</a></li>
		  	<li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-asc' %}">Titulos asc</a></li>
          	<li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-desc' %}">Titulos desc</a></li>
		  
		</ul>
	</div>
	<div class="row text-bg-dark p-4">
		<div class="col-12">
			<h4>Ultimas noticias</h4>
			<hr>
		</div>
		{% for n in object_list %}
		<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4 p-2">
			<img src="{{n.imagen.url}}" class="card-img-top" alt="..." style="height: 150px; object-fit: contain;">
			<div class="card-body">
				<div class="d-flex pb-2">
					{% for cat in n.categoria.all %}
					<div class="btn-categoria-{{cat.pk}}" style="width: 15px; height: 10px;" title="{{cat.nombre}}"></div>
					{% endfor %}
				</div>
				<h5 class="card-title">{{n.titulo}}</h5>
				<p><em>{{n.creado}}</em></p>
				<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer más</a>
			</div>
		</div>
		{% endfor %}

		<div class="col-12">
			<h4 class="my-3 pt-5">Otras noticias que quizas te interesen...</h>
			<hr>
		</div>
		<div class="d-lg-flex col-12 p-2">
			
			<div class="col-lg-6 col-md-12 p-1 text-center">

				<div class="text-center">
					<h1 class="fs-30 fw-bold">{{sola.titulo}}</h1>
					<!-- <h4 style="color: #999;">{{sola.descripcion}}</h4> -->
				</div>
				<h6>Fecha de publicacion: <em>{{sola.creado}}</em></h6>
				<h6>Autor: <em>{{sola.autor}}</em></h6>
				<hr>
				<img class="rounded mx-auto d-block pb-4" src="{{sola.imagen.url}}" alt="Imagen de la noticia" style="height: 250px; object-fit: contain;">
				<p style="color: #999;">{{sola.contenido|truncatechars:450}}</p>
				<a href="{% url 'noticias:detalle_noticia' sola.pk %}" class="btn btn-go">Leer más</a>
			</div>
			<div class="p-1">

				{% for n in otras %}
				<div class="text-bg-dark d-flex flex-row align-items-center p-3 border border-dark-subtle m-2 rounded">
					<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="text-decoration-none">
						<div class="card-body">
							<h5 style="color: #bbb;" class="card-title">{{n.titulo}}</h5>
							<div class="d-flex pt-2">
								{% for cat in n.categoria.all %}
								<div class="btn-categoria-{{cat.pk}}" style="width: 15px; height: 10px;" title="{{cat.nombre}}"></div>
								{% endfor %}
							</div>
						</div>
					</a>
				</div>
				{% endfor %}

			</div>

		</div>
		<hr>
	</div>
</div>
<hr>
{% endblock contenido %}

ProyectoFinal/templates/ord-fecha-desc.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container ">
		
	<div class="dropdown my-2">
		<button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
			<i class="fa fa-solid fa-filter"></i>
		</button>
		<ul class="dropdown-menu bg-dark text-light">
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'noticias:categorias' %}">Categorias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-fecha-desc' %}">Primeras noticias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-asc' %}">Titulos asc</a></li>
          <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-desc' %}">Titulos desc</a></li>
		</ul>
	</div>
	<div class="row text-bg-dark p-4">
		<div class="col-12">
			<h4>Primeras noticias</h4>
			<hr>
		</div>
			{% for n in object_list %}
			<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4">
				<img src="{{n.imagen.url}}" class="card-img-top my-2" alt="..." style="height: 150px; object-fit: contain;">
				<div class="d-flex">
					{% for cat in n.categoria.all %}
					<div class="btn-categoria-{{cat.pk}}" style="width: 15px; height: 10px;" title="{{cat.nombre}}"></div>
					{% endfor %}
					</div>
				<div class="card-body">
					<h5 class="card-title">{{n.titulo}}</h5>
					<p><em>{{n.creado}}</em></p>
					<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer más</a>
				</div>
			</div>
			{% endfor %}
	</div>
</div>
<hr>
{% endblock contenido %}

ProyectoFinal/templates/ord-tit-asc.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container ">
		
	<div class="dropdown my-2">
		<button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
			<i class="fa fa-solid fa-filter"></i>
		</button>
		<ul class="dropdown-menu bg-dark text-light">
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'noticias:categorias' %}">Categorias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-fecha-desc' %}">Primeras noticias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-asc' %}">Titulos asc</a></li>
          <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-desc' %}">Titulos desc</a></li>
		</ul>
	</div>
	<div class="row text-bg-dark p-4">
		<div class="col-12">
			<h4>Noticias ordenadas por titulo en orden ascendiente</h4>
			<hr>
		</div>
			{% for n in object_list %}
			<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4">
				<img src="{{n.imagen.url}}" class="card-img-top my-2" alt="..." style="height: 150px; object-fit: contain;">
				<div class="d-flex">
					{% for cat in n.categoria.all %}
					<div class="btn-categoria-{{cat.pk}}" style="width: 15px; height: 10px;" title="{{cat.nombre}}"></div>
					{% endfor %}
					</div>
				<div class="card-body">
					<h5 class="card-title">{{n.titulo}}</h5>
					<p><em>{{n.creado}}</em></p>
					<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer más</a>
				</div>
			</div>
			{% endfor %}
	</div>
</div>
<hr>
{% endblock contenido %}

ProyectoFinal/templates/ord-tit-desc.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container ">
		
	<div class="dropdown my-2">
		<button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
			<i class="fa fa-solid fa-filter"></i>
		</button>
		<ul class="dropdown-menu bg-dark text-light">
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'noticias:categorias' %}">Categorias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-fecha-desc' %}">Primeras noticias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-asc' %}">Titulos asc</a></li>
          <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-desc' %}">Titulos desc</a></li>
		</ul>
	</div>
	<div class="row text-bg-dark p-4">
		<div class="col-12">
			<h4>Noticias ordenadas por titulo en orden descendiente</h4>
			<hr>
		</div>
			{% for n in object_list %}
			<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4">
				<img src="{{n.imagen.url}}" class="card-img-top my-2" alt="..." style="height: 150px; object-fit: contain;">
				<div class="d-flex">
					{% for cat in n.categoria.all %}
					<div class="btn-categoria-{{cat.pk}}" style="width: 15px; height: 10px;" title="{{cat.nombre}}"></div>
					{% endfor %}
					</div>
				<div class="card-body">
					<h5 class="card-title">{{n.titulo}}</h5>
					<p><em>{{n.creado}}</em></p>
					<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer más</a>
				</div>
			</div>
			{% endfor %}
	</div>
</div>
<hr>
{% endblock contenido %}

ProyectoFinal/templates/sobre-nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container mt-3 text-bg-dark">
    <h3 class="pt-3">Sobre nosotros</h3>
    <p>Somos estudiantes de la 2da etapa ''Desarrollo Web'' del Informatorio. Conformamos un equipo de desarrollo de 5 integrantes, trabajando en conjunto y de manera remota. </p>
    <hr>
    <h3 class="">Sobre el proyecto</h3>
    <p> Este es un proyecto de tipo 'blog' creado enteramente por el grupo, el cual cuenta con las siguientes caracteristicas:</p>
    <li>Construido con el framework Django, utilizando Python como lenguaje de programación principal.</li>
    <li>Conectado a una base de datos sqlite3, para persistir registros de usuarios, fotos, noticias, etc.</li>
    <li>Para la interfaz visual utlizamos el lenguaje de marcado HTML para crear los templates y para agregarle estilos el framework de Boostrap, que utiliza el método de las clases.</li>
    <li>Fue desarrollado en el patron de arquitectura 'MVC', en django aplicado como 'MVT', Modelo Vista Template.</li>
    <hr>
    <h4>Miembros del equipo</h4>
        <div class="text-bg-dark">
            <ul class="ps-0 list-unstyled" >
                <li class="mt-3"><a target="_blank" href="https://github.com/universoparalelo" class="mx-3 fs-5 text-decoration-none icon2"><em>Celeste Martin Rodich </em><i class="mx-2 fa fa-brands fa-github icon2"></i></a></li>
                <li class="mt-3"><a target="_blank" href="https://github.com/Gabriel-Fernando-Vazquez" class="mx-3 fs-5 text-decoration-none icon2"><em>Gabriel Vazquez </em><i class="mx-2 fa fa-brands fa-github icon2"></i></a></li>
                <li class="mt-3"><a target="_blank" href="https://github.com/LeandroGomezz" class="mx-3 fs-5 text-decoration-none icon2"><em>Leandro Emanuel Gomez </em><i class="mx-2 fa fa-brands fa-github icon2"></i></a></li>
                <li class="mt-3"><a target="_blank" href="https://github.com/nicoguazo" class="mx-3 fs-5 text-decoration-none icon2"><em>Nicolas Alfredo Guazo </em><i class="mx-2 fa fa-brands fa-github icon2"></i></a></li>
                <li class="mt-3"><a target="_blank" href="https://github.com/FacundoLeiva12" class="mx-3 fs-5 text-decoration-none icon2"><em>Facundo Leiva </em><i class="mx-2 fa fa-brands fa-github icon2"></i></a></li>
            </ul>
        </div>
    <hr>
</div>
{% endblock contenido %}