proyectofinal/apps/noticias/urls.py
from django.urls import path, include
from . import views

app_name='noticias'

urlpatterns = [
    path('Crear', views.CrearNoticiaC.as_view(), name="crear_noticia"),
      # Noticias del usuario 
    path('mis-noticias', views.MisNoticias, name="misNoticias"),
     # Detalle de una noticia
    path('detalle-noticia/<int:pk>', views.DetalleNoticiaF, name='detalle_noticia'),
    
    path('Listar', views.ListarNoticiasF, name="listar_noticias"),

    path('Detalle/<int:pk>', views.DetalleNoticiaF, name="detalle_noticias"),

    path('Filtro/<int:pk>', views.Filtro_Categoria, name="filtro_categoria"),

    path('Borrar/<int:pk>', views.BorrarNoticia.as_view(), name="borrar_noticia"),

    path('Modificar/<int:pk>', views.ModificarNoticia.as_view(), name="modificar_noticia"),
   
    path('categorias', views.Categorias, name='categorias'),

    
   
   

]

proyectofinal/apps/usuarios/urls.py
from django.urls import path, include
from . import views

app_name='usuarios'

urlpatterns = [
    path('Registro', views.Registro.as_view(), name="registrar"),
]

proyectofinal/proyectofinal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name = 'home'),
    path('sobre-nosotros', views.SobreNosotros, name = 'sobre-nosotros'),
    path('contacto', views.Contacto, name = 'contacto'),

    #URLS DE AUTH
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    #URLS DE USUARIOS
    path('usuarios/', include('apps.usuarios.urls')),
    #URLS DE NOTICIAS
    path('noticias/', include('apps.noticias.urls')),
    # NOTICIAS ORDENADAS SEGUN...
    path('ord-fecha-desc/', views.OrdFechaDesc, name="ord-fecha-desc"),
    path('ord-tit-asc/', views.OrdTitAsc, name="ord-tit-asc"),
    path('ord-tit-desc/', views.OrdTitDesc, name="ord-tit-desc"),

     #URLS DE COMENTARIOS
    path('comentarios/', include('apps.comentarios.urls')),
    
     #URLS categorias-objetivos
    path('Categorias_objetivos', views.Categorias_objetivos, name='categorias_objetivos'),
      #Trea los objetivos de la categoria seleccionada
    path('objetivos/<int:categoria_id>/', views.objetivos_por_categoria, name = 'objetivos_categoria'),
    # Trae todas las categorias para buscar los objtivos

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectofinal/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- FONTAWESOME -->
    <script src="https://kit.fontawesome.com/b1758b74ef.js" crossorigin="anonymous"></script>

    <!-- STYLES -->
   
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

  </head>
  <body>
    <!-- HEADER -->
    <div class="header">
      <div class="container">
        <nav class="navbar navbar-expand-lg">
          <a class="navbar-brand" href="#"><i class="fa fa-brands fa-slack fs-4 fw-bold"></i></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link fs-6" aria-current="page" href="{% url 'home' %}" style="color: #bbb;">Inicio</a>
                
                <a class="nav-link fs-6" aria-current="page" href="{% url 'noticias:listar_noticias'%}" style="color: #bbb;">Noticias</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link fs-6" href="{% url 'noticias:misNoticias' %}" style="color: #bbb;">Mis noticias</a>
                <a class="nav-link fs-6" href="{% url 'noticias:crear_noticia' %}" style="color: #bbb;">Crear noticia</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link fs-6" href="{% url 'sobre-nosotros' %}" style="color: #bbb;">Sobre nosotros</a>
              </li>
              <li class="nav-item">
                <a class="nav-link fs-6" href="{% url 'contacto' %}" style="color: #bbb;">Contacto</a>
              </li>
            </ul>
            <div class="d-flex gap-3 mt-3 mb-2">
              {% if user.is_authenticated %}
              <a href="{% url 'logout' %}" class="fs-6 text-decoration-none log" style="color: #bbb;">Salir</a>
              {% else %}
              <a href="{% url 'login' %}" class="fs-6 text-decoration-none log" style="color: #bbb;">Iniciar sesión</a>
              <a href="{% url 'usuarios:registrar' %}" class="fs-6 text-decoration-none log" style="color: #bbb;">Registrarse</a>
              {% endif %}
            </div>
          </div>
        </nav>
      </div>
    </div>
    

    

    <!-- SECTION -->
    {% block contenido %}

    {% endblock contenido %}
    <!-- FOOTER -->
    <div class="footer mt-3">
      <div class="container text-center ">
        <div class="row">
          <div class="col-12 mb-3 mt-3">
            <img src="{% static 'img/slack.svg' %}" alt="" width="70px">
          </div>
          <div class="col-8 offset-sm-2 mb-3 fs-6">
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste et accusamus rerum hic blanditiis, expedita esse id, sequi provident ea sint modi vero numquam soluta? Illum labore dicta inventore possimus!</p>
          </div>
          <div class="col-12 mb-4">
            <a href="#" class="mx-3"><i class="fa fa-brands fa-facebook icon"></i></a>
            <a href="#" class="mx-3"><i class="fa fa-brands fa-instagram icon"></i></a>
            <a href="#" class="mx-3"><i class="fa fa-brands fa-envelope icon"></i></a>
            <a href="#" class="mx-3"><i class="fa fa-brands fa-linkedin icon"></i></a>
            <a href="#" class="mx-3"><i class="fa fa-brands fa-twitter icon"></i></a>
          </div>
          <div class="copyright col-12 mb-3">
            <h6>Copyright ©2023 All rights reserved | This template was made by <em>Grupo-2</em></h6>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    
  </body>

proyectofinal/templates/categorias-objetivos.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container m-3 p-2 text-bg-dark mx-auto">
    <div class="row">
        <h4 class="mb-3">Seleccione una categoria para ver los objetivos</h4>
        <hr class="mb-3">
    </div>
    <div class="row">
        {% for n in object_list %}
        <div class="card col-xs-12 col-sm-6 col-md-3 col-lg-2 bg-dark">
            <li>{{ categoria.nombre }}</li>
                <a href="{% url 'objetivos_categoria' n.pk %}" class="text-decoration-none">
                    <img class="img-cat d-block mx-auto" src="{{ n.imagen.url }}" alt="Imagen de la categoria">
                </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock contenido %}

proyectofinal/templates/contanto.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="container pb-5">
    <div class="row">
        <div class="section mt-3 text-bg-dark col-lg-8 offset-lg-2 col-sm-12 offset-sm-0">
            <h3 class="pt-3">Contáctanos</h3>
            <hr>

            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="floatingName" placeholder="Nombre">
                <label for="floatingName">Nombre</label>
            </div>

            <div class="form-floating mb-3">
                <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                <label for="floatingInput">Email</label>
            </div>

            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="floatingAsunto" placeholder="Asunto">
                <label for="floatingAsunto">Asunto</label>
            </div>

            <div class="form-floating mb-3">
                <textarea class="form-control" placeholder="Comentario" id="floatingTextarea"></textarea>
                <label for="floatingTextarea">Comentario</label>
            </div>
            <button type="submit" class="btn btn-go mx-auto d-block px-3 mb-3">Enviar</button>
        </div>
        
    </div>
</div>
{% endblock contenido %}

proyectofinal/templates/inicio.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container ">
		
	<div class="dropdown my-2">
		<button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
			<i class="fa fa-solid fa-filter"></i>
		</button>
		<ul class="dropdown-menu bg-dark text-light">
		 
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-fecha-desc' %}">Primeras noticias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-asc' %}">Titulos asc</a></li>
          <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-desc' %}">Titulos desc</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'categorias_objetivos' %}">Objetivos de metas</a></li>

		</ul>
	</div>
	<div class="row text-bg-dark p-4">
		<div class="col-12">
			<h4>Ultimas noticias</h4>
			<hr>
		</div>
		{% for n in object_list %}
		<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4 p-2">
			<img src="{{n.imagen.url}}" class="card-img-top" alt="..." style="height: 150px; object-fit: contain;">
			<div class="card-body">
				<p style="color: #999;">{{n.categoria}}</p>
				<h5 class="card-title">{{n.titulo}}</h5>
				<p>{{n.creado}}</p>
				<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer más</a>
			</div>
		</div>
		{% endfor %}
		<hr>
	</div>
</div>
<hr>
{% endblock contenido %}

proyectofinal/templates/objetivos.html
{% extends 'base.html' %}

{% block contenido %}

<div class=" container" style="text-align: center;padding-top: 40px;">
    <img src="{{categoria.imagen.url}}" style="border-radius: 10px;width: 35%;">
    <h1 style="color: aliceblue;text-align: center;">Objetivos de la categoría {{ categoria }}</h1>
    {% if objetivos %}
    <div class="container d-flex col-md-8" style="background-color:rgb(255, 255, 255);
    border-radius: 10px;text-align: start;padding-top: 10px;" >
        {% for objetivo in objetivos %}
            <h4>{{ categoria_seleccionada }}</h4>
        <div>
            {{ objetivo.Objetivos|linebreaks}} -
        </div>
        {% endfor %}
        {% else %}
            <p style="color: aliceblue;">No hay objetivos para esta categoría</p>
        {% endif %}
        </div>
    </div>
</div>


   
   


{% endblock contenido %}

proyectofinal/templates/ord-fecha-desc.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container ">
		
	<div class="dropdown my-2">
		<button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
			<i class="fa fa-solid fa-filter"></i>
		</button>
		<ul class="dropdown-menu bg-dark text-light">
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'noticias:categorias' %}">Categorias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-fecha-desc' %}">Primeras noticias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-asc' %}">Titulos asc</a></li>
          <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-desc' %}">Titulos desc</a></li>
		</ul>
	</div>
	<div class="row text-bg-dark p-4">
		<div class="col-12">
			<h4>Primeras noticias</h4>
			<hr>
		</div>
			{% for n in object_list %}
			<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4">
				<img src="{{n.imagen.url}}" class="card-img-top" alt="..." style="height: 150px; object-fit: contain;">
				<div class="card-body">
					<p style="color: #999;">{{n.categoria}}</p>
					<h5 class="card-title">{{n.titulo}}</h5>
					<p>{{n.creado}}</p>
					<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer más</a>
				</div>
			</div>
			{% endfor %}
	</div>
</div>
<hr>
{% endblock contenido %}

proyectofinal/templates/ord-tit-asc.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container ">
		
	<div class="dropdown my-2">
		<button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
			<i class="fa fa-solid fa-filter"></i>
		</button>
		<ul class="dropdown-menu bg-dark text-light">
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'noticias:categorias' %}">Categorias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-fecha-desc' %}">Primeras noticias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-asc' %}">Titulos asc</a></li>
          <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-desc' %}">Titulos desc</a></li>
		</ul>
	</div>
	<div class="row text-bg-dark p-4">
		<div class="col-12">
			<h4>Noticias ordenadas por titulo en orden ascendiente</h4>
			<hr>
		</div>
			{% for n in object_list %}
			<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4">
				<img src="{{n.imagen.url}}" class="card-img-top" alt="..." style="height: 150px; object-fit: contain;">
				<div class="card-body">
					<p style="color: #999;">{{n.categoria}}</p>
					<h5 class="card-title">{{n.titulo}}</h5>
					<p>{{n.creado}}</p>
					<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer más</a>
				</div>
			</div>
			{% endfor %}
	</div>
</div>
<hr>
{% endblock contenido %}

proyectofinal/templates/ord-tit-desc.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container ">
		
	<div class="dropdown my-2">
		<button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
			<i class="fa fa-solid fa-filter"></i>
		</button>
		<ul class="dropdown-menu bg-dark text-light">
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'noticias:categorias' %}">Categorias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-fecha-desc' %}">Primeras noticias</a></li>
		  <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-asc' %}">Titulos asc</a></li>
          <li><a class="dropdown-item bg-dark text-light" href="{% url 'ord-tit-desc' %}">Titulos desc</a></li>
		</ul>
	</div>
	<div class="row text-bg-dark p-4">
		<div class="col-12">
			<h4>Noticias ordenadas por titulo en orden descendiente</h4>
			<hr>
		</div>
			{% for n in object_list %}
			<div class="card text-bg-dark col-sm-12 col-md-6 col-lg-4">
				<img src="{{n.imagen.url}}" class="card-img-top" alt="..." style="height: 150px; object-fit: contain;">
				<div class="card-body">
					<p style="color: #999;">{{n.categoria}}</p>
					<h5 class="card-title">{{n.titulo}}</h5>
					<p>{{n.creado}}</p>
					<a href="{% url 'noticias:detalle_noticia' n.pk %}" class="btn btn-go">Leer más</a>
				</div>
			</div>
			{% endfor %}
	</div>
</div>
<hr>
{% endblock contenido %}

proyectofinal/templates/sobre-nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
<div class="section container mt-3 text-bg-dark">
<h3 class="pt-3">Sobre nosotros</h3>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste suscipit assumenda, labore deserunt doloribus, pariatur nulla incidunt quis impedit qui non! Rem, dolor quam iure sit eius itaque sunt sapiente!</p>
<hr>
<h4>Miembros del equipo</h4>
<div class="d-flex">
    <img src="{% static 'img/persona.jpg' %}" alt="" height="100px">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure quidem consequuntur distinctio quas voluptatibus ullam nulla vitae nisi repellendus reiciendis quam officiis tenetur itaque delectus maiores, laboriosam doloribus soluta maxime.</p>
</div>
<hr>
<div class="d-flex">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure quidem consequuntur distinctio quas voluptatibus ullam nulla vitae nisi repellendus reiciendis quam officiis tenetur itaque delectus maiores, laboriosam doloribus soluta maxime.</p>
    <img src="{% static 'img/persona.jpg' %}" alt="" height="100px">
</div>
<hr>
<div class="d-flex">
    <img src="{% static 'img/persona.jpg' %}" alt="" height="100px">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure quidem consequuntur distinctio quas voluptatibus ullam nulla vitae nisi repellendus reiciendis quam officiis tenetur itaque delectus maiores, laboriosam doloribus soluta maxime.</p>
</div>
<hr>
<div class="d-flex">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure quidem consequuntur distinctio quas voluptatibus ullam nulla vitae nisi repellendus reiciendis quam officiis tenetur itaque delectus maiores, laboriosam doloribus soluta maxime.</p>
    <img src="{% static 'img/persona.jpg' %}" alt="" height="100px">
</div>
<hr>
<div class="d-flex">
    <img src="{% static 'img/persona.jpg' %}" alt="" height="100px">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure quidem consequuntur distinctio quas voluptatibus ullam nulla vitae nisi repellendus reiciendis quam officiis tenetur itaque delectus maiores, laboriosam doloribus soluta maxime.</p>
</div>
<hr>
<div class="d-flex">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure quidem consequuntur distinctio quas voluptatibus ullam nulla vitae nisi repellendus reiciendis quam officiis tenetur itaque delectus maiores, laboriosam doloribus soluta maxime.</p>
    <img src="{% static 'img/persona.jpg' %}" alt="" height="100px">
</div>
<hr>
</div>
{% endblock contenido %}